/** @type {import('@remix-run/dev').AppConfig} */
export default {
    ignoredRouteFiles: ['**/.*'],
    appDirectory: 'src/app',
    tailwind: true,
    watchPaths: ['./src/components/**/*'],
    // assetsBuildDirectory: "public/build",
    // publicPath: "/build/",
    // serverBuildPath: "build/index.js",
    browserNodeBuiltinsPolyfill: {
        modules: {
            fs: true,
            url: true,
            os: true,
            path: true,
            http: true,
            https: true,
            events: true,
            zlib: true,
            stream: true,
            util: true,
            buffer: true,
            crypto: true,
            assert: true,
            net: true,
            punycode: true,
            child_process: true,
            querystring: true,
            tls: true,
        },
    },
}
